export type CreatePersonOutput = {
  readonly id: number;
  readonly uuid: string;
  readonly nombre: string;
  readonly nacimiento: string;
  readonly colorOjos: string;
  readonly genero: string;
  readonly colorCabello: string;
  readonly altura: string;
  readonly masa: string;
  readonly colorPiel: string;
  readonly mundoOrigen: string;
  readonly url: string;
  readonly fechaCreacion: Date;
  readonly fechaEdicion: Date;
  readonly especies: string[];
  readonly navesEspaciales: string[];
  readonly vehiculos: string[];
  readonly peliculas: string[];
};
